/*     */ package net.minecraft.client.model.geom;
/*     */ 
/*     */ import com.google.common.collect.ImmutableMap;
/*     */ import java.util.List;
/*     */ import java.util.Map;
/*     */ import net.minecraft.client.model.HumanoidModel;
/*     */ import net.minecraft.client.model.ambient.BatModel;
/*     */ import net.minecraft.client.model.animal.allay.AllayModel;
/*     */ import net.minecraft.client.model.animal.armadillo.ArmadilloModel;
/*     */ import net.minecraft.client.model.animal.axolotl.AxolotlModel;
/*     */ import net.minecraft.client.model.animal.bee.BeeModel;
/*     */ import net.minecraft.client.model.animal.bee.BeeStingerModel;
/*     */ import net.minecraft.client.model.animal.camel.CamelModel;
/*     */ import net.minecraft.client.model.animal.camel.CamelSaddleModel;
/*     */ import net.minecraft.client.model.animal.chicken.ChickenModel;
/*     */ import net.minecraft.client.model.animal.chicken.ColdChickenModel;
/*     */ import net.minecraft.client.model.animal.cow.ColdCowModel;
/*     */ import net.minecraft.client.model.animal.cow.CowModel;
/*     */ import net.minecraft.client.model.animal.cow.WarmCowModel;
/*     */ import net.minecraft.client.model.animal.dolphin.DolphinModel;
/*     */ import net.minecraft.client.model.animal.equine.AbstractEquineModel;
/*     */ import net.minecraft.client.model.animal.equine.DonkeyModel;
/*     */ import net.minecraft.client.model.animal.equine.EquineSaddleModel;
/*     */ import net.minecraft.client.model.animal.feline.CatModel;
/*     */ import net.minecraft.client.model.animal.feline.FelineModel;
/*     */ import net.minecraft.client.model.animal.fish.CodModel;
/*     */ import net.minecraft.client.model.animal.fish.PufferfishBigModel;
/*     */ import net.minecraft.client.model.animal.fish.PufferfishMidModel;
/*     */ import net.minecraft.client.model.animal.fish.PufferfishSmallModel;
/*     */ import net.minecraft.client.model.animal.fish.SalmonModel;
/*     */ import net.minecraft.client.model.animal.fish.TropicalFishLargeModel;
/*     */ import net.minecraft.client.model.animal.fish.TropicalFishSmallModel;
/*     */ import net.minecraft.client.model.animal.fox.FoxModel;
/*     */ import net.minecraft.client.model.animal.frog.FrogModel;
/*     */ import net.minecraft.client.model.animal.frog.TadpoleModel;
/*     */ import net.minecraft.client.model.animal.ghast.HappyGhastHarnessModel;
/*     */ import net.minecraft.client.model.animal.ghast.HappyGhastModel;
/*     */ import net.minecraft.client.model.animal.goat.GoatModel;
/*     */ import net.minecraft.client.model.animal.golem.CopperGolemModel;
/*     */ import net.minecraft.client.model.animal.golem.IronGolemModel;
/*     */ import net.minecraft.client.model.animal.golem.SnowGolemModel;
/*     */ import net.minecraft.client.model.animal.llama.LlamaModel;
/*     */ import net.minecraft.client.model.animal.llama.LlamaSpitModel;
/*     */ import net.minecraft.client.model.animal.nautilus.NautilusArmorModel;
/*     */ import net.minecraft.client.model.animal.nautilus.NautilusModel;
/*     */ import net.minecraft.client.model.animal.nautilus.NautilusSaddleModel;
/*     */ import net.minecraft.client.model.animal.panda.PandaModel;
/*     */ import net.minecraft.client.model.animal.parrot.ParrotModel;
/*     */ import net.minecraft.client.model.animal.pig.ColdPigModel;
/*     */ import net.minecraft.client.model.animal.pig.PigModel;
/*     */ import net.minecraft.client.model.animal.polarbear.PolarBearModel;
/*     */ import net.minecraft.client.model.animal.rabbit.RabbitModel;
/*     */ import net.minecraft.client.model.animal.sheep.SheepFurModel;
/*     */ import net.minecraft.client.model.animal.sheep.SheepModel;
/*     */ import net.minecraft.client.model.animal.sniffer.SnifferModel;
/*     */ import net.minecraft.client.model.animal.squid.SquidModel;
/*     */ import net.minecraft.client.model.animal.turtle.TurtleModel;
/*     */ import net.minecraft.client.model.animal.wolf.WolfModel;
/*     */ import net.minecraft.client.model.effects.EvokerFangsModel;
/*     */ import net.minecraft.client.model.effects.SpinAttackEffectModel;
/*     */ import net.minecraft.client.model.geom.builders.CubeDeformation;
/*     */ import net.minecraft.client.model.geom.builders.LayerDefinition;
/*     */ import net.minecraft.client.model.geom.builders.MeshDefinition;
/*     */ import net.minecraft.client.model.geom.builders.MeshTransformer;
/*     */ import net.minecraft.client.model.monster.blaze.BlazeModel;
/*     */ import net.minecraft.client.model.monster.breeze.BreezeModel;
/*     */ import net.minecraft.client.model.monster.creaking.CreakingModel;
/*     */ import net.minecraft.client.model.monster.creeper.CreeperModel;
/*     */ import net.minecraft.client.model.monster.dragon.EnderDragonModel;
/*     */ import net.minecraft.client.model.monster.enderman.EndermanModel;
/*     */ import net.minecraft.client.model.monster.endermite.EndermiteModel;
/*     */ import net.minecraft.client.model.monster.ghast.GhastModel;
/*     */ import net.minecraft.client.model.monster.guardian.GuardianModel;
/*     */ import net.minecraft.client.model.monster.hoglin.HoglinModel;
/*     */ import net.minecraft.client.model.monster.illager.IllagerModel;
/*     */ import net.minecraft.client.model.monster.nautilus.ZombieNautilusCoralModel;
/*     */ import net.minecraft.client.model.monster.phantom.PhantomModel;
/*     */ import net.minecraft.client.model.monster.piglin.PiglinModel;
/*     */ import net.minecraft.client.model.monster.ravager.RavagerModel;
/*     */ import net.minecraft.client.model.monster.shulker.ShulkerModel;
/*     */ import net.minecraft.client.model.monster.silverfish.SilverfishModel;
/*     */ import net.minecraft.client.model.monster.skeleton.BoggedModel;
/*     */ import net.minecraft.client.model.monster.skeleton.SkeletonModel;
/*     */ import net.minecraft.client.model.monster.slime.MagmaCubeModel;
/*     */ import net.minecraft.client.model.monster.slime.SlimeModel;
/*     */ import net.minecraft.client.model.monster.spider.SpiderModel;
/*     */ import net.minecraft.client.model.monster.strider.StriderModel;
/*     */ import net.minecraft.client.model.monster.vex.VexModel;
/*     */ import net.minecraft.client.model.monster.warden.WardenModel;
/*     */ import net.minecraft.client.model.monster.witch.WitchModel;
/*     */ import net.minecraft.client.model.monster.wither.WitherBossModel;
/*     */ import net.minecraft.client.model.monster.zombie.DrownedModel;
/*     */ import net.minecraft.client.model.monster.zombie.ZombieVillagerModel;
/*     */ import net.minecraft.client.model.npc.VillagerModel;
/*     */ import net.minecraft.client.model.object.armorstand.ArmorStandArmorModel;
/*     */ import net.minecraft.client.model.object.armorstand.ArmorStandModel;
/*     */ import net.minecraft.client.model.object.banner.BannerFlagModel;
/*     */ import net.minecraft.client.model.object.banner.BannerModel;
/*     */ import net.minecraft.client.model.object.bell.BellModel;
/*     */ import net.minecraft.client.model.object.boat.BoatModel;
/*     */ import net.minecraft.client.model.object.boat.RaftModel;
/*     */ import net.minecraft.client.model.object.book.BookModel;
/*     */ import net.minecraft.client.model.object.cart.MinecartModel;
/*     */ import net.minecraft.client.model.object.chest.ChestModel;
/*     */ import net.minecraft.client.model.object.crystal.EndCrystalModel;
/*     */ import net.minecraft.client.model.object.equipment.ElytraModel;
/*     */ import net.minecraft.client.model.object.equipment.ShieldModel;
/*     */ import net.minecraft.client.model.object.leash.LeashKnotModel;
/*     */ import net.minecraft.client.model.object.projectile.ArrowModel;
/*     */ import net.minecraft.client.model.object.projectile.ShulkerBulletModel;
/*     */ import net.minecraft.client.model.object.projectile.TridentModel;
/*     */ import net.minecraft.client.model.object.projectile.WindChargeModel;
/*     */ import net.minecraft.client.model.object.skull.DragonHeadModel;
/*     */ import net.minecraft.client.model.object.skull.PiglinHeadModel;
/*     */ import net.minecraft.client.model.object.skull.SkullModel;
/*     */ import net.minecraft.client.model.player.PlayerCapeModel;
/*     */ import net.minecraft.client.model.player.PlayerEarsModel;
/*     */ import net.minecraft.client.model.player.PlayerModel;
/*     */ import net.minecraft.client.renderer.blockentity.BedRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.ConduitRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.DecoratedPotRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.HangingSignRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.SignRenderer;
/*     */ import net.minecraft.client.renderer.entity.ArmorModelSet;
/*     */ import net.minecraft.client.renderer.entity.WitherSkullRenderer;
/*     */ import net.minecraft.world.level.block.state.properties.WoodType;
/*     */ 
/*     */ public class LayerDefinitions
/*     */ {
/* 130 */   private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008F);
/* 131 */   private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0F);
/* 132 */   private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5F);
/*     */   
/*     */   public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
/* 135 */     ImmutableMap.Builder<ModelLayerLocation, LayerDefinition> result = ImmutableMap.builder();
/*     */     
/* 137 */     LayerDefinition humanoidBodyLayer = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F), 64, 64);
/* 138 */     ArmorModelSet<LayerDefinition> humanoidArmor = HumanoidModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION).map(mesh -> LayerDefinition.create(mesh, 64, 32));
/* 139 */     ArmorModelSet<LayerDefinition> humanoidBabyArmor = humanoidArmor.map(layer -> layer.apply(HumanoidModel.BABY_TRANSFORMER));
/* 140 */     ArmorModelSet<LayerDefinition> playerArmor = PlayerModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION).map(mesh -> LayerDefinition.create(mesh, 64, 32));
/* 141 */     ArmorModelSet<LayerDefinition> piglinArmor = PiglinModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, new CubeDeformation(1.02F)).map(mesh -> LayerDefinition.create(mesh, 64, 32));
/* 142 */     ArmorModelSet<LayerDefinition> piglinBabyArmor = piglinArmor.map(layer -> layer.apply(HumanoidModel.BABY_TRANSFORMER));
/* 143 */     LayerDefinition minecartBodyLayer = MinecartModel.createBodyLayer();
/* 144 */     LayerDefinition mobHeadLayer = SkullModel.createMobHeadLayer();
/* 145 */     LayerDefinition horseBodyLayer = LayerDefinition.create(AbstractEquineModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
/* 146 */     LayerDefinition horseBabyLayer = LayerDefinition.create(AbstractEquineModel.createBabyMesh(CubeDeformation.NONE), 64, 64);
/* 147 */     LayerDefinition horseSaddleLayer = EquineSaddleModel.createSaddleLayer(false);
/* 148 */     LayerDefinition horseBabySaddleLayer = EquineSaddleModel.createSaddleLayer(true);
/* 149 */     MeshTransformer villagerLikeScale = MeshTransformer.scaling(0.9375F);
/* 150 */     LayerDefinition illagerBodyLayer = IllagerModel.createBodyLayer().apply(villagerLikeScale);
/* 151 */     LayerDefinition axolotlBodyLayer = AxolotlModel.createBodyLayer();
/* 152 */     LayerDefinition beeBodyLayer = BeeModel.createBodyLayer();
/* 153 */     LayerDefinition cowBodyLayer = CowModel.createBodyLayer();
/* 154 */     LayerDefinition coldChickenBodyLayer = ColdChickenModel.createBodyLayer();
/* 155 */     LayerDefinition coldCowBodyLayer = ColdCowModel.createBodyLayer();
/* 156 */     LayerDefinition coldPigBodyLayer = ColdPigModel.createBodyLayer(CubeDeformation.NONE);
/* 157 */     LayerDefinition elytraLayer = ElytraModel.createLayer();
/* 158 */     LayerDefinition felineBodyLayer = LayerDefinition.create(FelineModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
/* 159 */     LayerDefinition felineBabyBodyLayer = felineBodyLayer.apply(FelineModel.BABY_TRANSFORMER);
/* 160 */     LayerDefinition felineCollarLayer = LayerDefinition.create(FelineModel.createBodyMesh(new CubeDeformation(0.01F)), 64, 32);
/* 161 */     LayerDefinition piglinLayer = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
/* 162 */     LayerDefinition piglinHeadLayer = LayerDefinition.create(PiglinHeadModel.createHeadModel(), 64, 64);
/* 163 */     LayerDefinition humanoidHeadLayer = SkullModel.createHumanoidHeadLayer();
/* 164 */     LayerDefinition llamaBodyLayer = LlamaModel.createBodyLayer(CubeDeformation.NONE);
/* 165 */     LayerDefinition llamaDecorLayer = LlamaModel.createBodyLayer(new CubeDeformation(0.5F));
/* 166 */     LayerDefinition striderLayer = StriderModel.createBodyLayer();
/* 167 */     LayerDefinition hoglinLayer = HoglinModel.createBodyLayer();
/* 168 */     LayerDefinition hoglinBabyLayer = HoglinModel.createBabyLayer();
/* 169 */     LayerDefinition skeletonBodyLayer = SkeletonModel.createBodyLayer();
/* 170 */     LayerDefinition villagerBodyLayer = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64).apply(villagerLikeScale);
/* 171 */     LayerDefinition villagerNoHatLayer = LayerDefinition.create(VillagerModel.createNoHatModel(), 64, 64).apply(villagerLikeScale);
/* 172 */     LayerDefinition spiderBodyLayer = SpiderModel.createSpiderBodyLayer();
/* 173 */     LayerDefinition armadilloBodyLayer = ArmadilloModel.createBodyLayer();
/* 174 */     LayerDefinition camelBodyLayer = CamelModel.createBodyLayer();
/* 175 */     LayerDefinition camelSaddleLayer = CamelSaddleModel.createSaddleLayer();
/* 176 */     LayerDefinition chickenBodyLayer = ChickenModel.createBodyLayer();
/* 177 */     LayerDefinition goatBodyLayer = GoatModel.createBodyLayer();
/* 178 */     LayerDefinition pandaBodyLayer = PandaModel.createBodyLayer();
/* 179 */     LayerDefinition pigBodyLayer = PigModel.createBodyLayer(CubeDeformation.NONE);
/* 180 */     LayerDefinition pigSaddleLayer = PigModel.createBodyLayer(new CubeDeformation(0.5F));
/* 181 */     LayerDefinition sheepBodyLayer = SheepModel.createBodyLayer();
/* 182 */     LayerDefinition sheepWoolLayer = SheepFurModel.createFurLayer();
/* 183 */     LayerDefinition snifferBodyLayer = SnifferModel.createBodyLayer();
/* 184 */     LayerDefinition turtleBodyLayer = TurtleModel.createBodyLayer();
/* 185 */     LayerDefinition warmCowBodyLayer = WarmCowModel.createBodyLayer();
/* 186 */     LayerDefinition wolfBodyLayer = LayerDefinition.create(WolfModel.createMeshDefinition(CubeDeformation.NONE), 64, 32);
/* 187 */     LayerDefinition wolfArmorLayer = LayerDefinition.create(WolfModel.createMeshDefinition(new CubeDeformation(0.2F)), 64, 32);
/* 188 */     LayerDefinition zombieVillagerBodyLayer = ZombieVillagerModel.createBodyLayer();
/* 189 */     LayerDefinition zombieVillagerNoHatLayer = ZombieVillagerModel.createNoHatLayer();
/* 190 */     LayerDefinition armorStandBodyLayer = ArmorStandModel.createBodyLayer();
/* 191 */     ArmorModelSet<LayerDefinition> armorStandArmor = ArmorStandArmorModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
/* 192 */     LayerDefinition drownedBodyLayer = DrownedModel.createBodyLayer(CubeDeformation.NONE);
/* 193 */     LayerDefinition drownedOuterLayer = DrownedModel.createBodyLayer(new CubeDeformation(0.25F));
/* 194 */     LayerDefinition squidBodyLayer = SquidModel.createBodyLayer();
/* 195 */     LayerDefinition dolphinBodyLayer = DolphinModel.createBodyLayer();
/* 196 */     LayerDefinition salmonBodyLayer = SalmonModel.createBodyLayer();
/* 197 */     LayerDefinition nautilusSaddleLayer = NautilusSaddleModel.createSaddleLayer();
/*     */     
/* 199 */     result.put(ModelLayers.ALLAY, AllayModel.createBodyLayer());
/* 200 */     result.put(ModelLayers.ARMADILLO, armadilloBodyLayer);
/* 201 */     result.put(ModelLayers.ARMADILLO_BABY, armadilloBodyLayer.apply(ArmadilloModel.BABY_TRANSFORMER));
/* 202 */     result.put(ModelLayers.ARMOR_STAND, armorStandBodyLayer);
/* 203 */     ModelLayers.ARMOR_STAND_ARMOR.putFrom(armorStandArmor, result);
/* 204 */     result.put(ModelLayers.ARMOR_STAND_SMALL, armorStandBodyLayer.apply(HumanoidModel.BABY_TRANSFORMER));
/* 205 */     ModelLayers.ARMOR_STAND_SMALL_ARMOR.putFrom(armorStandArmor.map(layer -> layer.apply(HumanoidModel.BABY_TRANSFORMER)), result);
/* 206 */     result.put(ModelLayers.ARROW, ArrowModel.createBodyLayer());
/* 207 */     result.put(ModelLayers.AXOLOTL, axolotlBodyLayer);
/* 208 */     result.put(ModelLayers.AXOLOTL_BABY, axolotlBodyLayer.apply(AxolotlModel.BABY_TRANSFORMER));
/* 209 */     result.put(ModelLayers.STANDING_BANNER, BannerModel.createBodyLayer(true));
/* 210 */     result.put(ModelLayers.WALL_BANNER, BannerModel.createBodyLayer(false));
/* 211 */     result.put(ModelLayers.STANDING_BANNER_FLAG, BannerFlagModel.createFlagLayer(true));
/* 212 */     result.put(ModelLayers.WALL_BANNER_FLAG, BannerFlagModel.createFlagLayer(false));
/* 213 */     result.put(ModelLayers.BAT, BatModel.createBodyLayer());
/* 214 */     result.put(ModelLayers.BED_FOOT, BedRenderer.createFootLayer());
/* 215 */     result.put(ModelLayers.BED_HEAD, BedRenderer.createHeadLayer());
/* 216 */     result.put(ModelLayers.BEE, beeBodyLayer);
/* 217 */     result.put(ModelLayers.BEE_BABY, beeBodyLayer.apply(BeeModel.BABY_TRANSFORMER));
/* 218 */     result.put(ModelLayers.BEE_STINGER, BeeStingerModel.createBodyLayer());
/* 219 */     result.put(ModelLayers.BELL, BellModel.createBodyLayer());
/* 220 */     result.put(ModelLayers.BLAZE, BlazeModel.createBodyLayer());
/* 221 */     result.put(ModelLayers.BOAT_WATER_PATCH, BoatModel.createWaterPatch());
/* 222 */     result.put(ModelLayers.BOGGED, BoggedModel.createBodyLayer());
/* 223 */     ModelLayers.BOGGED_ARMOR.putFrom(humanoidArmor, result);
/* 224 */     result.put(ModelLayers.BOGGED_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.2F), 0.0F), 64, 32));
/* 225 */     result.put(ModelLayers.BOOK, BookModel.createBodyLayer());
/* 226 */     result.put(ModelLayers.BREEZE, BreezeModel.createBodyLayer());
/* 227 */     result.put(ModelLayers.BREEZE_WIND, BreezeModel.createWindLayer());
/* 228 */     result.put(ModelLayers.BREEZE_EYES, BreezeModel.createEyesLayer());
/* 229 */     result.put(ModelLayers.CAT, felineBodyLayer.apply(CatModel.CAT_TRANSFORMER));
/* 230 */     result.put(ModelLayers.CAT_BABY, felineBabyBodyLayer.apply(CatModel.CAT_TRANSFORMER));
/* 231 */     result.put(ModelLayers.CAT_COLLAR, felineCollarLayer.apply(CatModel.CAT_TRANSFORMER));
/* 232 */     result.put(ModelLayers.CAT_BABY_COLLAR, felineCollarLayer.apply(FelineModel.BABY_TRANSFORMER).apply(CatModel.CAT_TRANSFORMER));
/* 233 */     result.put(ModelLayers.CAMEL, camelBodyLayer);
/* 234 */     result.put(ModelLayers.CAMEL_BABY, camelBodyLayer.apply(CamelModel.BABY_TRANSFORMER));
/* 235 */     result.put(ModelLayers.CAMEL_SADDLE, camelSaddleLayer);
/* 236 */     result.put(ModelLayers.CAMEL_BABY_SADDLE, camelSaddleLayer.apply(CamelModel.BABY_TRANSFORMER));
/* 237 */     result.put(ModelLayers.CAMEL_HUSK_SADDLE, camelSaddleLayer);
/* 238 */     result.put(ModelLayers.CAMEL_HUSK_BABY_SADDLE, camelSaddleLayer.apply(CamelModel.BABY_TRANSFORMER));
/* 239 */     result.put(ModelLayers.CAVE_SPIDER, spiderBodyLayer.apply(MeshTransformer.scaling(0.7F)));
/* 240 */     result.put(ModelLayers.CHEST, ChestModel.createSingleBodyLayer());
/* 241 */     result.put(ModelLayers.CHEST_MINECART, minecartBodyLayer);
/* 242 */     result.put(ModelLayers.CHICKEN, chickenBodyLayer);
/* 243 */     result.put(ModelLayers.CHICKEN_BABY, chickenBodyLayer.apply(ChickenModel.BABY_TRANSFORMER));
/* 244 */     result.put(ModelLayers.COD, CodModel.createBodyLayer());
/* 245 */     result.put(ModelLayers.COLD_CHICKEN, coldChickenBodyLayer);
/* 246 */     result.put(ModelLayers.COLD_CHICKEN_BABY, coldChickenBodyLayer.apply(ChickenModel.BABY_TRANSFORMER));
/* 247 */     result.put(ModelLayers.COLD_COW, coldCowBodyLayer);
/* 248 */     result.put(ModelLayers.COLD_COW_BABY, coldCowBodyLayer.apply(CowModel.BABY_TRANSFORMER));
/* 249 */     result.put(ModelLayers.COLD_PIG, coldPigBodyLayer);
/* 250 */     result.put(ModelLayers.COLD_PIG_BABY, coldPigBodyLayer.apply(PigModel.BABY_TRANSFORMER));
/* 251 */     result.put(ModelLayers.COMMAND_BLOCK_MINECART, minecartBodyLayer);
/* 252 */     result.put(ModelLayers.CONDUIT_EYE, ConduitRenderer.createEyeLayer());
/* 253 */     result.put(ModelLayers.CONDUIT_WIND, ConduitRenderer.createWindLayer());
/* 254 */     result.put(ModelLayers.CONDUIT_SHELL, ConduitRenderer.createShellLayer());
/* 255 */     result.put(ModelLayers.CONDUIT_CAGE, ConduitRenderer.createCageLayer());
/* 256 */     result.put(ModelLayers.COPPER_GOLEM, CopperGolemModel.createBodyLayer());
/* 257 */     result.put(ModelLayers.COPPER_GOLEM_EYES, CopperGolemModel.createEyesLayer());
/* 258 */     result.put(ModelLayers.COPPER_GOLEM_RUNNING, CopperGolemModel.createRunningPoseBodyLayer());
/* 259 */     result.put(ModelLayers.COPPER_GOLEM_SITTING, CopperGolemModel.createSittingPoseBodyLayer());
/* 260 */     result.put(ModelLayers.COPPER_GOLEM_STAR, CopperGolemModel.createStarPoseBodyLayer());
/* 261 */     result.put(ModelLayers.COW, cowBodyLayer);
/* 262 */     result.put(ModelLayers.COW_BABY, cowBodyLayer.apply(CowModel.BABY_TRANSFORMER));
/* 263 */     result.put(ModelLayers.CREAKING, CreakingModel.createBodyLayer());
/* 264 */     result.put(ModelLayers.CREAKING_EYES, CreakingModel.createEyesLayer());
/* 265 */     result.put(ModelLayers.CREEPER, CreeperModel.createBodyLayer(CubeDeformation.NONE));
/* 266 */     result.put(ModelLayers.CREEPER_ARMOR, CreeperModel.createBodyLayer(new CubeDeformation(2.0F)));
/* 267 */     result.put(ModelLayers.CREEPER_HEAD, mobHeadLayer);
/* 268 */     result.put(ModelLayers.DECORATED_POT_BASE, DecoratedPotRenderer.createBaseLayer());
/* 269 */     result.put(ModelLayers.DECORATED_POT_SIDES, DecoratedPotRenderer.createSidesLayer());
/* 270 */     result.put(ModelLayers.DOLPHIN, dolphinBodyLayer);
/* 271 */     result.put(ModelLayers.DOLPHIN_BABY, dolphinBodyLayer.apply(DolphinModel.BABY_TRANSFORMER));
/* 272 */     result.put(ModelLayers.DONKEY, DonkeyModel.createBodyLayer(0.87F));
/* 273 */     result.put(ModelLayers.DONKEY_BABY, DonkeyModel.createBabyLayer(0.87F));
/* 274 */     result.put(ModelLayers.DONKEY_SADDLE, DonkeyModel.createSaddleLayer(0.87F, false));
/* 275 */     result.put(ModelLayers.DONKEY_BABY_SADDLE, DonkeyModel.createSaddleLayer(0.87F, true));
/* 276 */     result.put(ModelLayers.DOUBLE_CHEST_LEFT, ChestModel.createDoubleBodyLeftLayer());
/* 277 */     result.put(ModelLayers.DOUBLE_CHEST_RIGHT, ChestModel.createDoubleBodyRightLayer());
/* 278 */     result.put(ModelLayers.DRAGON_SKULL, DragonHeadModel.createHeadLayer());
/* 279 */     result.put(ModelLayers.DROWNED, drownedBodyLayer);
/* 280 */     ModelLayers.DROWNED_ARMOR.putFrom(humanoidArmor, result);
/* 281 */     result.put(ModelLayers.DROWNED_OUTER_LAYER, drownedOuterLayer);
/* 282 */     result.put(ModelLayers.DROWNED_BABY, drownedBodyLayer.apply(HumanoidModel.BABY_TRANSFORMER));
/* 283 */     ModelLayers.DROWNED_BABY_ARMOR.putFrom(humanoidBabyArmor, result);
/* 284 */     result.put(ModelLayers.DROWNED_BABY_OUTER_LAYER, drownedOuterLayer.apply(HumanoidModel.BABY_TRANSFORMER));
/* 285 */     result.put(ModelLayers.ELDER_GUARDIAN, GuardianModel.createElderGuardianLayer());
/* 286 */     result.put(ModelLayers.ELYTRA, elytraLayer);
/* 287 */     result.put(ModelLayers.ELYTRA_BABY, elytraLayer.apply(ElytraModel.BABY_TRANSFORMER));
/* 288 */     result.put(ModelLayers.ENDERMAN, EndermanModel.createBodyLayer());
/* 289 */     result.put(ModelLayers.ENDERMITE, EndermiteModel.createBodyLayer());
/* 290 */     result.put(ModelLayers.ENDER_DRAGON, EnderDragonModel.createBodyLayer());
/* 291 */     result.put(ModelLayers.END_CRYSTAL, EndCrystalModel.createBodyLayer());
/* 292 */     result.put(ModelLayers.EVOKER, illagerBodyLayer);
/* 293 */     result.put(ModelLayers.EVOKER_FANGS, EvokerFangsModel.createBodyLayer());
/* 294 */     result.put(ModelLayers.FOX, FoxModel.createBodyLayer());
/* 295 */     result.put(ModelLayers.FOX_BABY, FoxModel.createBodyLayer().apply(FoxModel.BABY_TRANSFORMER));
/* 296 */     result.put(ModelLayers.FROG, FrogModel.createBodyLayer());
/* 297 */     result.put(ModelLayers.FURNACE_MINECART, minecartBodyLayer);
/* 298 */     result.put(ModelLayers.GHAST, GhastModel.createBodyLayer());
/* 299 */     MeshTransformer giantScale = MeshTransformer.scaling(6.0F);
/* 300 */     result.put(ModelLayers.GIANT, humanoidBodyLayer.apply(giantScale));
/* 301 */     ModelLayers.GIANT_ARMOR.putFrom(humanoidArmor.map(layer -> layer.apply(giantScale)), result);
/* 302 */     result.put(ModelLayers.GLOW_SQUID, squidBodyLayer);
/* 303 */     result.put(ModelLayers.GLOW_SQUID_BABY, squidBodyLayer.apply(SquidModel.BABY_TRANSFORMER));
/* 304 */     result.put(ModelLayers.GOAT, goatBodyLayer);
/* 305 */     result.put(ModelLayers.GOAT_BABY, goatBodyLayer.apply(GoatModel.BABY_TRANSFORMER));
/* 306 */     result.put(ModelLayers.GUARDIAN, GuardianModel.createBodyLayer());
/* 307 */     result.put(ModelLayers.HAPPY_GHAST, HappyGhastModel.createBodyLayer(false, CubeDeformation.NONE));
/* 308 */     result.put(ModelLayers.HAPPY_GHAST_BABY, HappyGhastModel.createBodyLayer(true, CubeDeformation.NONE).apply(HappyGhastModel.BABY_TRANSFORMER));
/* 309 */     result.put(ModelLayers.HAPPY_GHAST_HARNESS, HappyGhastHarnessModel.createHarnessLayer(false));
/* 310 */     result.put(ModelLayers.HAPPY_GHAST_BABY_HARNESS, HappyGhastHarnessModel.createHarnessLayer(true).apply(HappyGhastModel.BABY_TRANSFORMER));
/* 311 */     result.put(ModelLayers.HAPPY_GHAST_ROPES, HappyGhastModel.createBodyLayer(false, new CubeDeformation(0.2F)));
/* 312 */     result.put(ModelLayers.HAPPY_GHAST_BABY_ROPES, HappyGhastModel.createBodyLayer(true, new CubeDeformation(0.2F)).apply(HappyGhastModel.BABY_TRANSFORMER));
/* 313 */     result.put(ModelLayers.HOGLIN, hoglinLayer);
/* 314 */     result.put(ModelLayers.HOGLIN_BABY, hoglinBabyLayer);
/* 315 */     result.put(ModelLayers.HOPPER_MINECART, minecartBodyLayer);
/* 316 */     MeshTransformer livingHorseScale = MeshTransformer.scaling(1.1F);
/* 317 */     result.put(ModelLayers.HORSE, horseBodyLayer.apply(livingHorseScale));
/* 318 */     result.put(ModelLayers.HORSE_BABY, horseBabyLayer.apply(livingHorseScale));
/* 319 */     result.put(ModelLayers.HORSE_ARMOR, LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64).apply(livingHorseScale));
/* 320 */     result.put(ModelLayers.HORSE_BABY_ARMOR, LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1F)), 64, 64).apply(livingHorseScale));
/* 321 */     result.put(ModelLayers.HORSE_SADDLE, horseSaddleLayer.apply(livingHorseScale));
/* 322 */     result.put(ModelLayers.HORSE_BABY_SADDLE, horseBabySaddleLayer.apply(livingHorseScale));
/* 323 */     MeshTransformer huskScale = MeshTransformer.scaling(1.0625F);
/* 324 */     result.put(ModelLayers.HUSK, humanoidBodyLayer.apply(huskScale));
/* 325 */     ModelLayers.HUSK_ARMOR.putFrom(humanoidArmor.map(layer -> layer.apply(huskScale)), result);
/* 326 */     result.put(ModelLayers.HUSK_BABY, humanoidBodyLayer.apply(HumanoidModel.BABY_TRANSFORMER).apply(huskScale));
/* 327 */     ModelLayers.HUSK_BABY_ARMOR.putFrom(humanoidBabyArmor.map(layer -> layer.apply(huskScale)), result);
/* 328 */     result.put(ModelLayers.ILLUSIONER, illagerBodyLayer);
/* 329 */     result.put(ModelLayers.IRON_GOLEM, IronGolemModel.createBodyLayer());
/* 330 */     result.put(ModelLayers.LEASH_KNOT, LeashKnotModel.createBodyLayer());
/* 331 */     result.put(ModelLayers.LLAMA, llamaBodyLayer);
/* 332 */     result.put(ModelLayers.LLAMA_BABY, llamaBodyLayer.apply(LlamaModel.BABY_TRANSFORMER));
/* 333 */     result.put(ModelLayers.LLAMA_DECOR, llamaDecorLayer);
/* 334 */     result.put(ModelLayers.LLAMA_BABY_DECOR, llamaDecorLayer.apply(LlamaModel.BABY_TRANSFORMER));
/* 335 */     result.put(ModelLayers.LLAMA_SPIT, LlamaSpitModel.createBodyLayer());
/* 336 */     result.put(ModelLayers.MAGMA_CUBE, MagmaCubeModel.createBodyLayer());
/* 337 */     result.put(ModelLayers.MINECART, minecartBodyLayer);
/* 338 */     result.put(ModelLayers.MOOSHROOM, cowBodyLayer);
/* 339 */     result.put(ModelLayers.MOOSHROOM_BABY, cowBodyLayer.apply(CowModel.BABY_TRANSFORMER));
/* 340 */     result.put(ModelLayers.MULE, DonkeyModel.createBodyLayer(0.92F));
/* 341 */     result.put(ModelLayers.MULE_BABY, DonkeyModel.createBabyLayer(0.92F));
/* 342 */     result.put(ModelLayers.MULE_SADDLE, DonkeyModel.createSaddleLayer(0.92F, false));
/* 343 */     result.put(ModelLayers.MULE_BABY_SADDLE, DonkeyModel.createSaddleLayer(0.92F, true));
/* 344 */     result.put(ModelLayers.NAUTILUS, NautilusModel.createBodyLayer());
/* 345 */     result.put(ModelLayers.NAUTILUS_BABY, NautilusModel.createBabyBodyLayer());
/* 346 */     result.put(ModelLayers.NAUTILUS_SADDLE, nautilusSaddleLayer);
/* 347 */     result.put(ModelLayers.NAUTILUS_ARMOR, NautilusArmorModel.createBodyLayer());
/* 348 */     result.put(ModelLayers.ZOMBIE_NAUTILUS, NautilusModel.createBodyLayer());
/* 349 */     result.put(ModelLayers.ZOMBIE_NAUTILUS_CORAL, ZombieNautilusCoralModel.createBodyLayer());
/* 350 */     result.put(ModelLayers.OCELOT, felineBodyLayer);
/* 351 */     result.put(ModelLayers.OCELOT_BABY, felineBabyBodyLayer);
/* 352 */     result.put(ModelLayers.PANDA, pandaBodyLayer);
/* 353 */     result.put(ModelLayers.PANDA_BABY, pandaBodyLayer.apply(PandaModel.BABY_TRANSFORMER));
/* 354 */     result.put(ModelLayers.PARCHED, SkeletonModel.createSingleModelDualBodyLayer());
/* 355 */     ModelLayers.PARCHED_ARMOR.putFrom(humanoidArmor, result);
/* 356 */     result.put(ModelLayers.PARCHED_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25F), 0.0F), 64, 32));
/* 357 */     result.put(ModelLayers.PARROT, ParrotModel.createBodyLayer());
/* 358 */     result.put(ModelLayers.PHANTOM, PhantomModel.createBodyLayer());
/* 359 */     result.put(ModelLayers.PIG, pigBodyLayer);
/* 360 */     result.put(ModelLayers.PIG_BABY, pigBodyLayer.apply(PigModel.BABY_TRANSFORMER));
/* 361 */     result.put(ModelLayers.PIG_SADDLE, pigSaddleLayer);
/* 362 */     result.put(ModelLayers.PIG_BABY_SADDLE, pigSaddleLayer.apply(PigModel.BABY_TRANSFORMER));
/* 363 */     result.put(ModelLayers.PIGLIN, piglinLayer);
/* 364 */     ModelLayers.PIGLIN_ARMOR.putFrom(piglinArmor, result);
/* 365 */     result.put(ModelLayers.PIGLIN_BRUTE, piglinLayer);
/* 366 */     ModelLayers.PIGLIN_BRUTE_ARMOR.putFrom(piglinArmor, result);
/* 367 */     result.put(ModelLayers.PIGLIN_BABY, piglinLayer.apply(HumanoidModel.BABY_TRANSFORMER));
/* 368 */     ModelLayers.PIGLIN_BABY_ARMOR.putFrom(piglinBabyArmor, result);
/* 369 */     result.put(ModelLayers.PIGLIN_HEAD, piglinHeadLayer);
/* 370 */     result.put(ModelLayers.PILLAGER, illagerBodyLayer);
/* 371 */     result.put(ModelLayers.PLAYER, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
/* 372 */     result.put(ModelLayers.PLAYER_EARS, PlayerEarsModel.createEarsLayer());
/* 373 */     result.put(ModelLayers.PLAYER_CAPE, PlayerCapeModel.createCapeLayer());
/* 374 */     result.put(ModelLayers.PLAYER_HEAD, humanoidHeadLayer);
/* 375 */     ModelLayers.PLAYER_ARMOR.putFrom(playerArmor, result);
/* 376 */     result.put(ModelLayers.PLAYER_SLIM, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
/* 377 */     ModelLayers.PLAYER_SLIM_ARMOR.putFrom(playerArmor, result);
/* 378 */     result.put(ModelLayers.PLAYER_SPIN_ATTACK, SpinAttackEffectModel.createLayer());
/* 379 */     result.put(ModelLayers.POLAR_BEAR, PolarBearModel.createBodyLayer(false));
/* 380 */     result.put(ModelLayers.POLAR_BEAR_BABY, PolarBearModel.createBodyLayer(true));
/* 381 */     result.put(ModelLayers.PUFFERFISH_BIG, PufferfishBigModel.createBodyLayer());
/* 382 */     result.put(ModelLayers.PUFFERFISH_MEDIUM, PufferfishMidModel.createBodyLayer());
/* 383 */     result.put(ModelLayers.PUFFERFISH_SMALL, PufferfishSmallModel.createBodyLayer());
/* 384 */     result.put(ModelLayers.RABBIT, RabbitModel.createBodyLayer(false));
/* 385 */     result.put(ModelLayers.RABBIT_BABY, RabbitModel.createBodyLayer(true));
/* 386 */     result.put(ModelLayers.RAVAGER, RavagerModel.createBodyLayer());
/* 387 */     result.put(ModelLayers.SALMON, salmonBodyLayer);
/* 388 */     result.put(ModelLayers.SALMON_SMALL, salmonBodyLayer.apply(SalmonModel.SMALL_TRANSFORMER));
/* 389 */     result.put(ModelLayers.SALMON_LARGE, salmonBodyLayer.apply(SalmonModel.LARGE_TRANSFORMER));
/* 390 */     result.put(ModelLayers.SHEEP, sheepBodyLayer);
/* 391 */     result.put(ModelLayers.SHEEP_BABY, sheepBodyLayer.apply(SheepModel.BABY_TRANSFORMER));
/* 392 */     result.put(ModelLayers.SHEEP_WOOL, sheepWoolLayer);
/* 393 */     result.put(ModelLayers.SHEEP_BABY_WOOL, sheepWoolLayer.apply(SheepModel.BABY_TRANSFORMER));
/* 394 */     result.put(ModelLayers.SHEEP_WOOL_UNDERCOAT, sheepBodyLayer);
/* 395 */     result.put(ModelLayers.SHEEP_BABY_WOOL_UNDERCOAT, sheepBodyLayer.apply(SheepModel.BABY_TRANSFORMER));
/* 396 */     result.put(ModelLayers.SHIELD, ShieldModel.createLayer());
/* 397 */     result.put(ModelLayers.SHULKER, ShulkerModel.createBodyLayer());
/* 398 */     result.put(ModelLayers.SHULKER_BOX, ShulkerModel.createBoxLayer());
/* 399 */     result.put(ModelLayers.SHULKER_BULLET, ShulkerBulletModel.createBodyLayer());
/* 400 */     result.put(ModelLayers.SILVERFISH, SilverfishModel.createBodyLayer());
/* 401 */     result.put(ModelLayers.SKELETON, skeletonBodyLayer);
/* 402 */     ModelLayers.SKELETON_ARMOR.putFrom(humanoidArmor, result);
/* 403 */     result.put(ModelLayers.SKELETON_HORSE, horseBodyLayer);
/* 404 */     result.put(ModelLayers.SKELETON_HORSE_BABY, horseBabyLayer);
/* 405 */     result.put(ModelLayers.SKELETON_HORSE_SADDLE, horseSaddleLayer);
/* 406 */     result.put(ModelLayers.SKELETON_HORSE_BABY_SADDLE, horseBabySaddleLayer);
/* 407 */     result.put(ModelLayers.SKELETON_SKULL, mobHeadLayer);
/* 408 */     result.put(ModelLayers.SLIME, SlimeModel.createInnerBodyLayer());
/* 409 */     result.put(ModelLayers.SLIME_OUTER, SlimeModel.createOuterBodyLayer());
/* 410 */     result.put(ModelLayers.SNIFFER, snifferBodyLayer);
/* 411 */     result.put(ModelLayers.SNIFFER_BABY, snifferBodyLayer.apply(SnifferModel.BABY_TRANSFORMER));
/* 412 */     result.put(ModelLayers.SNOW_GOLEM, SnowGolemModel.createBodyLayer());
/* 413 */     result.put(ModelLayers.SPAWNER_MINECART, minecartBodyLayer);
/* 414 */     result.put(ModelLayers.SPIDER, spiderBodyLayer);
/* 415 */     result.put(ModelLayers.SQUID, squidBodyLayer);
/* 416 */     result.put(ModelLayers.SQUID_BABY, squidBodyLayer.apply(SquidModel.BABY_TRANSFORMER));
/* 417 */     result.put(ModelLayers.STRAY, skeletonBodyLayer);
/* 418 */     ModelLayers.STRAY_ARMOR.putFrom(humanoidArmor, result);
/* 419 */     result.put(ModelLayers.STRAY_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25F), 0.0F), 64, 32));
/* 420 */     result.put(ModelLayers.STRIDER, striderLayer);
/* 421 */     result.put(ModelLayers.STRIDER_SADDLE, striderLayer);
/* 422 */     result.put(ModelLayers.STRIDER_BABY, striderLayer.apply(StriderModel.BABY_TRANSFORMER));
/* 423 */     result.put(ModelLayers.STRIDER_BABY_SADDLE, striderLayer.apply(StriderModel.BABY_TRANSFORMER));
/* 424 */     result.put(ModelLayers.TADPOLE, TadpoleModel.createBodyLayer());
/* 425 */     result.put(ModelLayers.TNT_MINECART, minecartBodyLayer);
/* 426 */     result.put(ModelLayers.TRADER_LLAMA, llamaBodyLayer);
/* 427 */     result.put(ModelLayers.TRADER_LLAMA_BABY, llamaBodyLayer.apply(LlamaModel.BABY_TRANSFORMER));
/* 428 */     result.put(ModelLayers.TRIDENT, TridentModel.createLayer());
/* 429 */     result.put(ModelLayers.TROPICAL_FISH_LARGE, TropicalFishLargeModel.createBodyLayer(CubeDeformation.NONE));
/* 430 */     result.put(ModelLayers.TROPICAL_FISH_LARGE_PATTERN, TropicalFishLargeModel.createBodyLayer(FISH_PATTERN_DEFORMATION));
/* 431 */     result.put(ModelLayers.TROPICAL_FISH_SMALL, TropicalFishSmallModel.createBodyLayer(CubeDeformation.NONE));
/* 432 */     result.put(ModelLayers.TROPICAL_FISH_SMALL_PATTERN, TropicalFishSmallModel.createBodyLayer(FISH_PATTERN_DEFORMATION));
/* 433 */     result.put(ModelLayers.TURTLE, turtleBodyLayer);
/* 434 */     result.put(ModelLayers.TURTLE_BABY, turtleBodyLayer.apply(TurtleModel.BABY_TRANSFORMER));
/* 435 */     result.put(ModelLayers.UNDEAD_HORSE_ARMOR, LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64));
/* 436 */     result.put(ModelLayers.UNDEAD_HORSE_BABY_ARMOR, LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1F)), 64, 64));
/* 437 */     result.put(ModelLayers.VEX, VexModel.createBodyLayer());
/* 438 */     result.put(ModelLayers.VILLAGER, villagerBodyLayer);
/* 439 */     result.put(ModelLayers.VILLAGER_NO_HAT, villagerNoHatLayer);
/* 440 */     result.put(ModelLayers.VILLAGER_BABY, villagerBodyLayer.apply(VillagerModel.BABY_TRANSFORMER));
/* 441 */     result.put(ModelLayers.VILLAGER_BABY_NO_HAT, villagerNoHatLayer.apply(VillagerModel.BABY_TRANSFORMER));
/* 442 */     result.put(ModelLayers.VINDICATOR, illagerBodyLayer);
/* 443 */     result.put(ModelLayers.WARDEN, WardenModel.createBodyLayer());
/* 444 */     result.put(ModelLayers.WARDEN_TENDRILS, WardenModel.createTendrilsLayer());
/* 445 */     result.put(ModelLayers.WARDEN_HEART, WardenModel.createHeartLayer());
/* 446 */     result.put(ModelLayers.WARDEN_BIOLUMINESCENT, WardenModel.createBioluminescentLayer());
/* 447 */     result.put(ModelLayers.WARDEN_PULSATING_SPOTS, WardenModel.createPulsatingSpotsLayer());
/* 448 */     result.put(ModelLayers.WARM_COW, warmCowBodyLayer);
/* 449 */     result.put(ModelLayers.WARM_COW_BABY, warmCowBodyLayer.apply(CowModel.BABY_TRANSFORMER));
/* 450 */     result.put(ModelLayers.WANDERING_TRADER, villagerBodyLayer);
/* 451 */     result.put(ModelLayers.WIND_CHARGE, WindChargeModel.createBodyLayer());
/* 452 */     result.put(ModelLayers.WITCH, WitchModel.createBodyLayer().apply(villagerLikeScale));
/* 453 */     result.put(ModelLayers.WITHER, WitherBossModel.createBodyLayer(CubeDeformation.NONE));
/* 454 */     result.put(ModelLayers.WITHER_ARMOR, WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
/* 455 */     result.put(ModelLayers.WITHER_SKULL, WitherSkullRenderer.createSkullLayer());
/* 456 */     MeshTransformer witherSkeletonScale = MeshTransformer.scaling(1.2F);
/* 457 */     result.put(ModelLayers.WITHER_SKELETON, skeletonBodyLayer.apply(witherSkeletonScale));
/* 458 */     ModelLayers.WITHER_SKELETON_ARMOR.putFrom(humanoidArmor.map(layer -> layer.apply(witherSkeletonScale)), result);
/* 459 */     result.put(ModelLayers.WITHER_SKELETON_SKULL, mobHeadLayer);
/* 460 */     result.put(ModelLayers.WOLF, wolfBodyLayer);
/* 461 */     result.put(ModelLayers.WOLF_ARMOR, wolfArmorLayer);
/* 462 */     result.put(ModelLayers.WOLF_BABY, wolfBodyLayer.apply(WolfModel.BABY_TRANSFORMER));
/* 463 */     result.put(ModelLayers.WOLF_BABY_ARMOR, wolfArmorLayer.apply(WolfModel.BABY_TRANSFORMER));
/* 464 */     result.put(ModelLayers.ZOGLIN, hoglinLayer);
/* 465 */     result.put(ModelLayers.ZOGLIN_BABY, hoglinBabyLayer);
/* 466 */     result.put(ModelLayers.ZOMBIE, humanoidBodyLayer);
/* 467 */     ModelLayers.ZOMBIE_ARMOR.putFrom(humanoidArmor, result);
/* 468 */     result.put(ModelLayers.ZOMBIE_BABY, humanoidBodyLayer.apply(HumanoidModel.BABY_TRANSFORMER));
/* 469 */     ModelLayers.ZOMBIE_BABY_ARMOR.putFrom(humanoidBabyArmor, result);
/* 470 */     result.put(ModelLayers.ZOMBIE_HEAD, humanoidHeadLayer);
/* 471 */     result.put(ModelLayers.ZOMBIE_HORSE, horseBodyLayer);
/* 472 */     result.put(ModelLayers.ZOMBIE_HORSE_BABY, horseBabyLayer);
/* 473 */     result.put(ModelLayers.ZOMBIE_HORSE_SADDLE, horseSaddleLayer);
/* 474 */     result.put(ModelLayers.ZOMBIE_HORSE_BABY_SADDLE, horseBabySaddleLayer);
/* 475 */     result.put(ModelLayers.ZOMBIE_VILLAGER, zombieVillagerBodyLayer);
/* 476 */     result.put(ModelLayers.ZOMBIE_VILLAGER_NO_HAT, zombieVillagerNoHatLayer);
/* 477 */     ArmorModelSet<LayerDefinition> zombieVillagerArmor = ZombieVillagerModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
/* 478 */     ModelLayers.ZOMBIE_VILLAGER_ARMOR.putFrom(zombieVillagerArmor, result);
/* 479 */     result.put(ModelLayers.ZOMBIE_VILLAGER_BABY, zombieVillagerBodyLayer.apply(HumanoidModel.BABY_TRANSFORMER));
/* 480 */     result.put(ModelLayers.ZOMBIE_VILLAGER_BABY_NO_HAT, zombieVillagerNoHatLayer.apply(HumanoidModel.BABY_TRANSFORMER));
/* 481 */     ModelLayers.ZOMBIE_VILLAGER_BABY_ARMOR.putFrom(zombieVillagerArmor.map(layer -> layer.apply(HumanoidModel.BABY_TRANSFORMER)), result);
/* 482 */     result.put(ModelLayers.ZOMBIFIED_PIGLIN, piglinLayer);
/* 483 */     ModelLayers.ZOMBIFIED_PIGLIN_ARMOR.putFrom(piglinArmor, result);
/* 484 */     result.put(ModelLayers.ZOMBIFIED_PIGLIN_BABY, piglinLayer.apply(HumanoidModel.BABY_TRANSFORMER));
/* 485 */     ModelLayers.ZOMBIFIED_PIGLIN_BABY_ARMOR.putFrom(piglinBabyArmor, result);
/*     */     
/* 487 */     result.put(ModelLayers.BAMBOO_RAFT, RaftModel.createRaftModel());
/* 488 */     result.put(ModelLayers.BAMBOO_CHEST_RAFT, RaftModel.createChestRaftModel());
/*     */     
/* 490 */     LayerDefinition boatModel = BoatModel.createBoatModel();
/* 491 */     LayerDefinition chestBoatModel = BoatModel.createChestBoatModel();
/* 492 */     result.put(ModelLayers.OAK_BOAT, boatModel);
/* 493 */     result.put(ModelLayers.OAK_CHEST_BOAT, chestBoatModel);
/* 494 */     result.put(ModelLayers.SPRUCE_BOAT, boatModel);
/* 495 */     result.put(ModelLayers.SPRUCE_CHEST_BOAT, chestBoatModel);
/* 496 */     result.put(ModelLayers.BIRCH_BOAT, boatModel);
/* 497 */     result.put(ModelLayers.BIRCH_CHEST_BOAT, chestBoatModel);
/* 498 */     result.put(ModelLayers.JUNGLE_BOAT, boatModel);
/* 499 */     result.put(ModelLayers.JUNGLE_CHEST_BOAT, chestBoatModel);
/* 500 */     result.put(ModelLayers.ACACIA_BOAT, boatModel);
/* 501 */     result.put(ModelLayers.ACACIA_CHEST_BOAT, chestBoatModel);
/* 502 */     result.put(ModelLayers.CHERRY_BOAT, boatModel);
/* 503 */     result.put(ModelLayers.CHERRY_CHEST_BOAT, chestBoatModel);
/* 504 */     result.put(ModelLayers.DARK_OAK_BOAT, boatModel);
/* 505 */     result.put(ModelLayers.DARK_OAK_CHEST_BOAT, chestBoatModel);
/* 506 */     result.put(ModelLayers.PALE_OAK_BOAT, boatModel);
/* 507 */     result.put(ModelLayers.PALE_OAK_CHEST_BOAT, chestBoatModel);
/* 508 */     result.put(ModelLayers.MANGROVE_BOAT, boatModel);
/* 509 */     result.put(ModelLayers.MANGROVE_CHEST_BOAT, chestBoatModel);
/*     */     
/* 511 */     LayerDefinition standingSignModel = SignRenderer.createSignLayer(true);
/* 512 */     LayerDefinition wallSignModel = SignRenderer.createSignLayer(false);
/* 513 */     WoodType.values().forEach(woodType -> {
/*     */           result.put(ModelLayers.createStandingSignModelName(woodType), standingSignModel);
/*     */           
/*     */           result.put(ModelLayers.createWallSignModelName(woodType), wallSignModel);
/*     */           for (HangingSignRenderer.AttachmentType attachmentType : HangingSignRenderer.AttachmentType.values()) {
/*     */             LayerDefinition hangingSignModel = HangingSignRenderer.createHangingSignLayer(attachmentType);
/*     */             result.put(ModelLayers.createHangingSignModelName(woodType, attachmentType), hangingSignModel);
/*     */           } 
/*     */         });
/* 522 */     ImmutableMap<ModelLayerLocation, LayerDefinition> definitions = result.build();
/* 523 */     List<ModelLayerLocation> missingDefinitions = ModelLayers.getKnownLocations().filter(l -> !definitions.containsKey(l)).toList();
/* 524 */     if (!missingDefinitions.isEmpty()) {
/* 525 */       throw new IllegalStateException("Missing layer definitions: " + String.valueOf(missingDefinitions));
/*     */     }
/* 527 */     return (Map<ModelLayerLocation, LayerDefinition>)definitions;
/*     */   }
/*     */ }


/* Location:              /home/carlos/.minecraft/versions/1.21.11_unobfuscated/1.21.11_unobfuscated.jar!/net/minecraft/client/model/geom/LayerDefinitions.class
 * Java compiler version: 21 (65.0)
 * JD-Core Version:       1.2.3
 */